### ISSUE TITLE
(public) Alchemy Language api key

### ISSUE THREAD

**Issue by blblblu** [AirVan21/BookTravel#8]
Hi,
just wanted to let you know that you (probably accidentally) published your Watson Alchemy Language api key, in case you wanted to keep that private ;)

https://github.com/AirVan21/BookTravel/blob/b2bf27dfe56cf71942eb52e0d4851a5c15a9eab6/backend/src/main/java/ru/spbau/books/decisions/WatsonSentimentJudge.java#L13

**Comment by AirVan21** [comment]
Hi Sebastian,

Thank you for your comment. You are 100% right that private should be private.
Fixed it! (hope nobody will search commit-diff history)

And I'm just curious about how you have noticed this? (I thought that I am the only person who have ever seen this code:) )

**Comment by blblblu** [comment]
Well, I just started to use AlchemyLanguage, and was kind of curious whether or not it would be possible to (mis)use the GitHub search to find valid api keys (like you can find for example a lot of database logins or ssh keys on GitHub), and (before you removed it) your Code was one of the first search results for "alchemylab api_key".

**Comment by AirVan21** [comment]
Yep, I see.

My key was a trial-key for a month, so I didn't pay attention to security) 

And thank you for a comment one more time.
